=== release-engineering/cdn-definitions/src/cdn_definitions/schema.json
{
    "$id": "http://release-engineering.github.io/cdn-definitions/schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "absolute_path": {
            "pattern": "^/",
            "type": "string"
        },
        "arch": {
            "type": "string"
        },
        "arch_list": {
            "items": {
                "$ref": "#/definitions/arch"
            },
            "type": "array",
            "uniqueItems": true
        },
        "beta_and_ga_keys_mapping": {
            "additionalProperties": false,
            "properties": {
                "beta_keys": {
                    "$ref": "#/definitions/signing_key_list"
                },
                "ga_keys": {
                    "$ref": "#/definitions/signing_key_list"
                }
            },
            "required": [
                "ga_keys"
            ],
            "type": "object"
        },
        "cfme_version_mappings_list": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/major_or_release_version"
                }
            },
            "propertyNames": {
                "$ref": "#/definitions/major_or_release_version"
            },
            "type": "object"
        },
        "content_set_label": {
            "pattern": "^[A-Za-z0-9_\\-]{1,200}$",
            "type": "string"
        },
        "content_set_to_release_version_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/release_version"
                }
            },
            "propertyNames": {
                "$ref": "#/definitions/content_set_label"
            },
            "type": "object"
        },
        "current_latest_rhel_versions": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/release_version"
                        }
                    ]
                }
            },
            "propertyNames": {
                "pattern": "^(current|latest)\\_rhel[0-9]+\\_(beta|dist)$",
                "type": "string"
            },
            "type": "object"
        },
        "directory_layout": {
            "additionalProperties": false,
            "properties": {
                "arch": {
                    "$ref": "#/definitions/arch"
                },
                "layered_product": {
                    "type": "string"
                },
                "layered_product_version": {
                    "type": "string"
                },
                "major_version": {
                    "$ref": "#/definitions/major_version_string"
                },
                "minor_version": {
                    "$ref": "#/definitions/major_version_string"
                },
                "name": {
                    "type": "string"
                },
                "pattern": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "product": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "rhelalt": {
                    "type": "boolean"
                },
                "rhui": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                },
                "variant": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "pattern"
            ],
            "type": "object"
        },
        "directory_layouts": {
            "items": {
                "$ref": "#/definitions/directory_layout"
            },
            "type": "array",
            "uniqueItems": true
        },
        "env_to_releasever_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/current_latest_rhel_versions"
                }
            },
            "type": "object"
        },
        "exclude_versions_from_listings": {
            "items": {
                "$ref": "#/definitions/release_version"
            },
            "type": "array",
            "uniqueItems": true
        },
        "iso8601_datetime": {
            "anyOf": [
                {
                    "format": "date"
                },
                {
                    "format": "date-time"
                }
            ],
            "type": "string"
        },
        "major_or_release_version": {
            "pattern": "^[0-9]+(\\.[0-9]+)*$",
            "type": "string"
        },
        "major_to_release_version_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/release_version"
                }
            },
            "propertyNames": {
                "$ref": "#/definitions/major_version_string"
            },
            "type": "object"
        },
        "major_version": {
            "type": "integer"
        },
        "major_version_list": {
            "items": {
                "$ref": "#/definitions/major_version"
            },
            "type": "array",
            "uniqueItems": true
        },
        "major_version_string": {
            "pattern": "^[0-9]+$",
            "type": "string"
        },
        "major_version_to_signing_keys_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/beta_and_ga_keys_mapping"
                }
            },
            "propertyNames": {
                "$ref": "#/definitions/major_version_string"
            }
        },
        "path_alias": {
            "additionalProperties": false,
            "properties": {
                "dest": {
                    "$ref": "#/definitions/absolute_path"
                },
                "src": {
                    "$ref": "#/definitions/absolute_path"
                }
            },
            "required": [
                "src",
                "dest"
            ],
            "type": "object"
        },
        "path_alias_list": {
            "items": {
                "$ref": "#/definitions/path_alias"
            },
            "type": "array",
            "uniqueItems": true
        },
        "product_id": {
            "pattern": "^[0-9]+$",
            "type": "string"
        },
        "product_id_list": {
            "items": {
                "$ref": "#/definitions/product_id"
            },
            "type": "array",
            "uniqueItems": true
        },
        "release_stream_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/release_version_list"
                }
            },
            "type": "object"
        },
        "release_version": {
            "pattern": "^[0-9]+\\.[0-9]+$",
            "type": "string"
        },
        "release_version_list": {
            "items": {
                "$ref": "#/definitions/release_version"
            },
            "type": "array",
            "uniqueItems": true
        },
        "repo_content_sync": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "items": {
                        "$ref": "#/definitions/repo_content_sync_record"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "repo_content_sync_record": {
            "additionalProperties": false,
            "properties": {
                "populate_dot_repos": {
                    "type": "boolean"
                },
                "source": {
                    "type": "string"
                },
                "branch_prefix": {
                  "type": "string"   
                }
            },
            "type": "object"
        },
        "repo_override": {
            "additionalProperties": false,
            "allOf": [
                {
                    "required": [
                        "key",
                        "value"
                    ]
                },
                {
                    "anyOf": [
                        {
                            "required": [
                                "if_match_id"
                            ]
                        },
                        {
                            "required": [
                                "if_match_path"
                            ]
                        },
                        {
                            "required": [
                                "if_created_before"
                            ]
                        },
                        {
                            "required": [
                                "if_created_after"
                            ]
                        }
                    ]
                }
            ],
            "properties": {
                "if_created_after": {
                    "$ref": "#/definitions/iso8601_datetime"
                },
                "if_created_before": {
                    "$ref": "#/definitions/iso8601_datetime"
                },
                "if_match_id": {
                    "type": "string"
                },
                "if_match_path": {
                    "$ref": "#/definitions/absolute_path"
                },
                "key": {
                    "minLength": 1,
                    "type": "string"
                },
                "value": {
                    "type": [
                        "string",
                        "boolean",
                        "number"
                    ]
                }
            },
            "type": "object"
        },
        "repo_overrides": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "items": {
                        "$ref": "#/definitions/repo_override"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "signing_key": {
            "pattern": "^[A-F0-9]{8}$",
            "type": "string"
        },
        "signing_key_list": {
            "items": {
                "$ref": "#/definitions/signing_key"
            },
            "type": "array",
            "uniqueItems": true
        },
        "signing_keys_mapping": {
            "additionalProperties": false,
            "properties": {
                "default": {
                    "$ref": "#/definitions/beta_and_ga_keys_mapping"
                },
                "layered_product": {
                    "$ref": "#/definitions/string_to_signing_keys_mapping"
                },
                "major_version": {
                    "$ref": "#/definitions/major_version_to_signing_keys_mapping"
                },
                "platform": {
                    "$ref": "#/definitions/string_to_signing_keys_mapping"
                }
            },
            "required": [
                "layered_product",
                "platform",
                "major_version"
            ],
            "type": "object"
        },
        "string_to_signing_keys_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/beta_and_ga_keys_mapping"
                }
            }
        },
        "symlink_exception_list": {
            "items": {
                "$ref": "#/definitions/absolute_path"
            },
            "type": "array",
            "uniqueItems": true
        },
        "tps_variant_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "version_to_arch_list_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/arch_list"
                }
            },
            "propertyNames": {
                "$ref": "#/definitions/major_version_string"
            },
            "type": "object"
        }
    },
    "properties": {
        "cfme_version_mappings": {
            "$ref": "#/definitions/cfme_version_mappings_list"
        },
        "directory_layouts": {
            "$ref": "#/definitions/directory_layouts"
        },
        "env_to_releasever_mappings": {
            "$ref": "#/definitions/env_to_releasever_mapping"
        },
        "exclude_from_listings": {
            "$ref": "#/definitions/exclude_versions_from_listings"
        },
        "filter_arches_from_release": {
            "$ref": "#/definitions/version_to_arch_list_mapping"
        },
        "ignore_lp_version_product_ids": {
            "$ref": "#/definitions/product_id_list"
        },
        "origin_alias": {
            "$ref": "#/definitions/path_alias_list"
        },
        "override_final_rhel_release": {
            "$ref": "#/definitions/content_set_to_release_version_mapping"
        },
        "override_initial_rhel_release": {
            "$ref": "#/definitions/major_to_release_version_mapping"
        },
        "populate_ubi_dot_repos": {
            "type": "boolean"
        },
        "release_stream_mappings": {
            "$ref": "#/definitions/release_stream_mapping"
        },
        "releasever_alias": {
            "$ref": "#/definitions/path_alias_list"
        },
        "repo_content_sync": {
            "$ref": "#/definitions/repo_content_sync"
        },
        "repo_overrides": {
            "$ref": "#/definitions/repo_overrides"
        },
        "rhel_open_dist": {
            "$ref": "#/definitions/major_version_list"
        },
        "rhui_alias": {
            "$ref": "#/definitions/path_alias_list"
        },
        "rhui_product_id": {
            "$ref": "#/definitions/product_id"
        },
        "rhui_product_ids": {
            "$ref": "#/definitions/product_id_list"
        },
        "signing_keys_mappings": {
            "$ref": "#/definitions/signing_keys_mapping"
        },
        "symlink_exceptions": {
            "$ref": "#/definitions/symlink_exception_list"
        },
        "tps_variant_mappings": {
            "$ref": "#/definitions/tps_variant_mapping"
        },
        "version": {
            "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
            "type": "string"
        }
    },
    "type": "object"
}

=== release-engineering/cdn-definitions/src/cdn_definitions/data.json
{
    "cfme_version_mappings": {
        "0.0": "0.0"
    },
    "directory_layouts": [
        {
            "layered_product_version": "5.8",
            "major_version": "6",
            "name": "ChannelDumpsLayout",
            "pattern": "(?x)^\n/\n(?:content|shadow)/\n(?P<type>aus|dist|beta|(?:retired-)?els|eus|htb|rhb|tus|e4s)/\n(?P<platform>rhel)/\n(?P<rhui>rhui/)?\n(?P<variant>[^/]+)/\n(?P<major_version>[0-9][^/]*)/\n(?:[567](?:Client|ComputeNode|Server|Workstation|Everything))/\n(?P<arch>[^/]+)/\n(?:channel\\-dumps/.+)"
        },
        {
            "name": "DirectoryLayoutC",
            "pattern": "(?x)^\n/\n(?:content|shadow)/\n(?P<type>aus|dist|beta|(?:retired-)?els|eus|htb|rhb|tus|e4s)/\n(?P<platform>rhes|rhs|cf-me)/\n(?P<rhui>rhui/)?\n(?P<variant>[^/]+)/\n(?P<major_version>[0-9])\\.(?P<minor_version>[0-9]+)/\n(?P<arch>[^/]+)/"
        },
        {
            "name": "DirectoryLayoutD",
            "pattern": "(?x)^\n(?P<up_to_minor>\n  /\n  (?:content|shadow)/\n  (?P<type>aus|dist|beta|(?:retired-)?els|eus|fastrack|htb|rhb|tus|e4s)/\n  (?P<platform>cf-me|rhel|rhevh|rhes|rhs)/\n  (?P<rhui>rhui/)?(?P<variant>[^/]+)/\n  (?P<major_version>[0-7][^/]*)\n)\n/\n(?P<minor_version>(?:\\$releasever|\\$[0-9]+|[34][AEW]S|[34]Desktop))/\n(?P<arch>[^/]+)/"
        },
        {
            "name": "DirectoryLayoutE",
            "pattern": "(?x)^\n/\n(?:content|shadow)/\n(?P<type>aus|dist|beta|(?:retired-)?els|eus|fastrack|htb|rhb|rc|preview|tus|e4s)/\n(?P<platform>arm|cf-me|rhel|rhevh|rhes|rhs)/\n(?P<rhui>rhui/)?\n(?P<variant>[^/]+)/\n(?P<major_version>[0-9][^./]*)/\n(?P<arch>(?:arm|aarch64|ppc64|s390x|x86_64|multiarch|\\$basearch))/"
        },
        {
            "name": "DirectoryLayoutF",
            "pattern": "(?x)^\n/\n(?:content|shadow)/\n(?P<type>aus|dist|beta|(?:retired-)?els|eus|fastrack|htb|rhb|preview|tus|e4s)/\n(?P<platform>cf-me|rhel|rhevh|rhes|rhs)/\n(?P<rhui>rhui/)?\n(?P<variant>[^/]+)/\n(?P<major_version>[0-9][^/]*)/\n(?:[567](?:Client|ComputeNode|Server|Workstation|Everything))/\n(?P<arch>(?:ppc64|s390x|x86_64|multiarch|\\$basearch))/\n(?!channel-dumps/)"
        },
        {
            "name": "RhelAltLayout",
            "pattern": "(?x)^\n/\n(?:content|shadow)/\n(?P<type>aus|dist|beta|(?:retired-)?els|eus|htb|rhb|tus|e4s)/\n(?P<platform>rhel-alt)/\n(?P<rhui>rhui/)?\n(?P<variant>[^/]+)/\n(?P<major_version>[0-9])/\n(\n  (\\$releasever)|7(Server|Client|ComputeNode|Workstation)|[0-9]\\.\n  (?P<minor_version>[0-9]+)\n)\n/\n(?P<vendor_arch>[^/]+)/\n(?P<arch>[^/]+)/",
            "platform": "rhel",
            "rhelalt": true
        },
        {
            "arch": "x86_64",
            "major_version": "6",
            "name": "ContentISOsLayout",
            "pattern": "(?x)^\n/\ncontent/\ncontentisos(?:/)?",
            "platform": "rhel",
            "type": "dist"
        },
        {
            "arch": "x86_64",
            "name": "SLESLayout",
            "pattern": "(?x)^\n/\ncontent/\n(?P<type>dist|beta)/\nsuse/server/\n(?P<major_version>11|12|15)/\n(?P<minor_version>sp[\\d])/?",
            "platform": "suse"
        },
        {
            "name": "PublicRepoFileLayout",
            "pattern": "(?x)^\n/\ncontent/\npublic/\nrepofiles$",
            "repo": "files",
            "type": "dist"
        }
    ],
    "env_to_releasever_mappings": {
        "prod": {
            "current_rhel0_beta": "0.0",
            "current_rhel0_dist": "0.0",
            "latest_rhel0_beta": "0.0",
            "latest_rhel0_dist": "0.0"
        },
        "qa": {
            "current_rhel0_beta": "0.0",
            "current_rhel0_dist": "0.0",
            "latest_rhel0_beta": "0.0",
            "latest_rhel0_dist": "0.0"
        },
        "stage": {
            "current_rhel0_beta": "0.0",
            "current_rhel0_dist": "0.0",
            "latest_rhel0_beta": "0.0",
            "latest_rhel0_dist": null
        }
    },
    "exclude_from_listings": [
        "0.0"
    ],
    "filter_arches_from_release": {
        "0": [
            "example_64"
        ]
    },
    "ignore_lp_version_product_ids": [
        "000"
    ],
    "origin_alias": [
        {
            "dest": "/origin",
            "src": "/content/origin"
        },
        {
            "dest": "/origin/rpms",
            "src": "/origin/rpm"
        }
    ],
    "override_final_rhel_release": {
        "cs_label_example": "0.0"
    },
    "override_initial_rhel_release": {
        "0": "0.0"
    },
    "release_stream_mappings": {
        "aus": [
            "0.0"
        ],
        "e4s": [
            "0.0"
        ],
        "eus": [
            "0.0"
        ],
        "other": [
            "0.0"
        ],
        "tus": [
            "0.0"
        ]
    },
    "releasever_alias": [
        {
            "dest": "/content/dist/rhel0/0.9",
            "src": "/content/dist/rhel0/0"
        },
        {
            "dest": "/content/dist/rhel1/1.11",
            "src": "/content/dist/rhel1/1"
        }
    ],
    "repo_content_sync": {
        "prod": [
            {
                "populate_dot_repos": false,
                "source": "https://example.com/ubi/data",
                "branch_prefix": "ubi"
            },
            {
                "populate_dot_repos": true,
                "source": "https://example.com/client-tools/data"
            }
        ],
        "stage": [
            {
                "populate_dot_repos": false,
                "source": "https://example.com/ubi/data",
                "branch_prefix": "ubi"
            },
            {
                "populate_dot_repos": true,
                "source": "https://example.com/client-tools/data"
            }
        ]
    },
    "repo_overrides": {
        "prod": [
            {
                "if_match_path": "/content/dist/rhel9/",
                "key": "example",
                "value": true
            },
            {
                "if_created_after": "2023-06-01T14:00:00Z",
                "if_match_id": "rhel-8",
                "key": "example",
                "value": true
            }
        ],
        "stage": [
            {
                "if_match_id": ".",
                "key": "example",
                "value": true
            },
            {
                "if_match_id": "e2e.*rhel-8",
                "key": "example",
                "value": false
            }
        ]
    },
    "rhel_open_dist": [
        0
    ],
    "rhui_alias": [
        {
            "dest": "/content/aus/rhel8",
            "src": "/content/aus/rhel8/rhui"
        },
        {
            "dest": "/content/aus/rhel",
            "src": "/content/aus/rhel/rhui"
        },
        {
            "dest": "/content/beta/rhel8",
            "src": "/content/beta/rhel8/rhui"
        },
        {
            "dest": "/content/beta/rhel-alt",
            "src": "/content/beta/rhel-alt/rhui"
        },
        {
            "dest": "/content/beta/rhel",
            "src": "/content/beta/rhel/rhui"
        },
        {
            "dest": "/content/beta/rhs",
            "src": "/content/beta/rhs/rhui"
        },
        {
            "dest": "/content/dist/layered",
            "src": "/content/dist/layered/rhui"
        },
        {
            "dest": "/content/dist/middleware",
            "src": "/content/dist/middleware/rhui"
        },
        {
            "dest": "/content/dist/rhel8",
            "src": "/content/dist/rhel8/rhui"
        },
        {
            "dest": "/content/dist/rhel-alt",
            "src": "/content/dist/rhel-alt/rhui"
        },
        {
            "dest": "/content/dist/rhel",
            "src": "/content/dist/rhel/rhui"
        },
        {
            "dest": "/content/dist/rhes",
            "src": "/content/dist/rhes/rhui"
        },
        {
            "dest": "/content/dist/rhs",
            "src": "/content/dist/rhs/rhui"
        },
        {
            "dest": "/content/e4s/rhel8",
            "src": "/content/e4s/rhel8/rhui"
        },
        {
            "dest": "/content/e4s/rhel",
            "src": "/content/e4s/rhel/rhui"
        },
        {
            "dest": "/content/els/rhel",
            "src": "/content/els/rhel/rhui"
        },
        {
            "dest": "/content/eus/rhel8",
            "src": "/content/eus/rhel8/rhui"
        },
        {
            "dest": "/content/eus/rhel",
            "src": "/content/eus/rhel/rhui"
        },
        {
            "dest": "/content/rc/rhel",
            "src": "/content/rc/rhel/rhui"
        }
    ],
    "rhui_product_ids": [
        "000",
        "001"
    ],
    "signing_keys_mappings": {
        "default": {
            "beta_keys": [
                "BBBBBBBB"
            ],
            "ga_keys": [
                "00000000"
            ]
        },
        "layered_product": {
            "example-lp": {
                "ga_keys": [
                    "00000000"
                ]
            }
        },
        "major_version": {
            "0": {
                "beta_keys": [
                    "BBBBBBBB"
                ],
                "ga_keys": [
                    "00000000"
                ]
            }
        },
        "platform": {
            "example_none": {
                "ga_keys": []
            },
            "example_platform": {
                "beta_keys": [
                    "BBBBBBBB"
                ],
                "ga_keys": [
                    "FFFFFFFF"
                ]
            }
        }
    },
    "symlink_exceptions": [
        "/this/is/an/example/"
    ],
    "tps_variant_mappings": {
        "example-arch": "Example-Variant"
    },
    "version": "1.3.0"
}
